use crate::root_store::RootStoreError;
use libsqlite3_sys as sqlite;
use std::ffi::CStr;
use std::ffi::CString;
use std::path::Path;
use std::ptr;

const ROOT_STORE_APPLICATION_ID: i64 = 1_380_076_620;
pub(crate) const ROOT_STORE_SCHEMA_VERSION: i64 = 1;
// Present in the pinned macOS sqlite3.h but omitted by the minimum-version
// bindings generated by libsqlite3-sys.
const SQLITE_OPEN_EXRESCODE: i32 = 0x0200_0000;

const RELEASE_EPOCHS_SQL: &str = r#"CREATE TABLE release_epochs(
  release_sequence INTEGER PRIMARY KEY CHECK(release_sequence>0),
  lease_epoch INTEGER NOT NULL UNIQUE CHECK(lease_epoch>0),
  UNIQUE(release_sequence,lease_epoch)
)"#;
const GUARD_METADATA_SQL: &str = r#"CREATE TABLE guard_metadata(
  singleton INTEGER PRIMARY KEY CHECK(singleton=1),
  schema_version INTEGER NOT NULL,
  release_sequence INTEGER NOT NULL CHECK(release_sequence>0),
  lease_epoch INTEGER NOT NULL CHECK(lease_epoch>0),
  revision INTEGER NOT NULL CHECK(revision>0),
  lifecycle TEXT NOT NULL CHECK(lifecycle IN ('active','quiescing')),
  FOREIGN KEY(release_sequence,lease_epoch) REFERENCES release_epochs(release_sequence,lease_epoch)
)"#;
const ACTOR_AUTHORITIES_SQL: &str = r#"CREATE TABLE actor_authorities(
  role TEXT PRIMARY KEY,
  component_tuple_digest TEXT NOT NULL,
  release_sequence INTEGER NOT NULL,
  lease_epoch INTEGER NOT NULL,
  FOREIGN KEY(release_sequence,lease_epoch) REFERENCES release_epochs(release_sequence,lease_epoch)
)"#;
const BROKER_OPERATIONS_SQL: &str = r#"CREATE TABLE broker_operations(
  operation_id TEXT PRIMARY KEY,
  authorizing_gateway_tuple_digest TEXT NOT NULL,
  subject_digest TEXT NOT NULL,
  payload_digest TEXT NOT NULL,
  broker_role TEXT NOT NULL CHECK(broker_role IN ('model','network','current-state')),
  release_sequence INTEGER NOT NULL,
  lease_epoch INTEGER NOT NULL,
  state TEXT NOT NULL CHECK(state IN ('authorized','claimed','effect-starting','settled-safe','effect-unknown','cancelled-no-effect')),
  effect_attempt_count INTEGER NOT NULL CHECK(effect_attempt_count IN (0,1)),
  owner_instance TEXT,
  revision INTEGER NOT NULL CHECK(revision>0),
  settlement_digest TEXT,
  CHECK((state IN ('authorized','claimed','cancelled-no-effect') AND effect_attempt_count=0) OR (state IN ('effect-starting','settled-safe','effect-unknown') AND effect_attempt_count=1)),
  CHECK((state IN ('authorized','cancelled-no-effect') AND owner_instance IS NULL) OR (state NOT IN ('authorized','cancelled-no-effect') AND owner_instance IS NOT NULL)),
  FOREIGN KEY(release_sequence,lease_epoch) REFERENCES release_epochs(release_sequence,lease_epoch)
)"#;
const RELEASE_REVOCATIONS_SQL: &str = r#"CREATE TABLE release_revocations(
  release_sequence INTEGER PRIMARY KEY,
  revoked_at_revision INTEGER NOT NULL,
  FOREIGN KEY(release_sequence) REFERENCES release_epochs(release_sequence)
)"#;
const BROKER_NO_DELETE_SQL: &str = "CREATE TRIGGER broker_operations_no_delete BEFORE DELETE ON broker_operations BEGIN SELECT RAISE(ABORT,'broker operations are append-only'); END";
const BROKER_TRANSITION_SQL: &str = r#"CREATE TRIGGER broker_operations_transition BEFORE UPDATE ON broker_operations WHEN NOT (
  NEW.operation_id=OLD.operation_id AND
  NEW.authorizing_gateway_tuple_digest=OLD.authorizing_gateway_tuple_digest AND
  NEW.subject_digest=OLD.subject_digest AND
  NEW.payload_digest=OLD.payload_digest AND
  NEW.broker_role=OLD.broker_role AND
  NEW.release_sequence=OLD.release_sequence AND
  NEW.lease_epoch=OLD.lease_epoch AND
  NEW.revision=OLD.revision+1 AND
  (
    (OLD.state='authorized' AND NEW.state='claimed' AND OLD.effect_attempt_count=0 AND NEW.effect_attempt_count=0 AND OLD.owner_instance IS NULL AND NEW.owner_instance IS NOT NULL AND OLD.settlement_digest IS NULL AND NEW.settlement_digest IS NULL) OR
    (OLD.state='authorized' AND NEW.state='cancelled-no-effect' AND OLD.effect_attempt_count=0 AND NEW.effect_attempt_count=0 AND OLD.owner_instance IS NULL AND NEW.owner_instance IS NULL AND OLD.settlement_digest IS NULL AND NEW.settlement_digest IS NULL) OR
    (OLD.state='claimed' AND NEW.state='effect-starting' AND OLD.effect_attempt_count=0 AND NEW.effect_attempt_count=1 AND NEW.owner_instance=OLD.owner_instance AND OLD.settlement_digest IS NULL AND NEW.settlement_digest IS NULL) OR
    (OLD.state='effect-starting' AND NEW.state='settled-safe' AND OLD.effect_attempt_count=1 AND NEW.effect_attempt_count=1 AND NEW.owner_instance=OLD.owner_instance AND OLD.settlement_digest IS NULL AND NEW.settlement_digest IS NOT NULL) OR
    (OLD.state='effect-starting' AND NEW.state='effect-unknown' AND OLD.effect_attempt_count=1 AND NEW.effect_attempt_count=1 AND NEW.owner_instance=OLD.owner_instance AND OLD.settlement_digest IS NULL AND NEW.settlement_digest IS NULL)
  )
) BEGIN SELECT RAISE(ABORT,'invalid broker operation transition'); END"#;
const RELEASE_EPOCHS_NO_DELETE_SQL: &str = "CREATE TRIGGER release_epochs_no_delete BEFORE DELETE ON release_epochs BEGIN SELECT RAISE(ABORT,'release epochs are append-only'); END";
const REVOCATIONS_NO_DELETE_SQL: &str = "CREATE TRIGGER release_revocations_no_delete BEFORE DELETE ON release_revocations BEGIN SELECT RAISE(ABORT,'release revocations are append-only'); END";
const REVOCATIONS_NO_UPDATE_SQL: &str = "CREATE TRIGGER release_revocations_no_update BEFORE UPDATE ON release_revocations BEGIN SELECT RAISE(ABORT,'release revocations are immutable'); END";

const SCHEMA_OBJECTS: &[(&str, &str, &str, &str)] = &[
    (
        "table",
        "release_epochs",
        "release_epochs",
        RELEASE_EPOCHS_SQL,
    ),
    (
        "table",
        "guard_metadata",
        "guard_metadata",
        GUARD_METADATA_SQL,
    ),
    (
        "table",
        "actor_authorities",
        "actor_authorities",
        ACTOR_AUTHORITIES_SQL,
    ),
    (
        "table",
        "broker_operations",
        "broker_operations",
        BROKER_OPERATIONS_SQL,
    ),
    (
        "table",
        "release_revocations",
        "release_revocations",
        RELEASE_REVOCATIONS_SQL,
    ),
    (
        "trigger",
        "broker_operations_no_delete",
        "broker_operations",
        BROKER_NO_DELETE_SQL,
    ),
    (
        "trigger",
        "broker_operations_transition",
        "broker_operations",
        BROKER_TRANSITION_SQL,
    ),
    (
        "trigger",
        "release_epochs_no_delete",
        "release_epochs",
        RELEASE_EPOCHS_NO_DELETE_SQL,
    ),
    (
        "trigger",
        "release_revocations_no_delete",
        "release_revocations",
        REVOCATIONS_NO_DELETE_SQL,
    ),
    (
        "trigger",
        "release_revocations_no_update",
        "release_revocations",
        REVOCATIONS_NO_UPDATE_SQL,
    ),
];

pub(crate) struct RootSqlite {
    raw: *mut sqlite::sqlite3,
}

impl RootSqlite {
    pub(crate) fn open(path: &Path, created: bool) -> Result<Self, RootStoreError> {
        let path = CString::new(path.as_os_str().as_encoded_bytes())
            .map_err(|_| RootStoreError::InvalidRoot("database path contains NUL".to_string()))?;
        let mut raw = ptr::null_mut();
        let mut flags = sqlite::SQLITE_OPEN_READWRITE
            | sqlite::SQLITE_OPEN_FULLMUTEX
            | sqlite::SQLITE_OPEN_PRIVATECACHE
            | sqlite::SQLITE_OPEN_NOFOLLOW
            | SQLITE_OPEN_EXRESCODE;
        if created {
            flags |= sqlite::SQLITE_OPEN_CREATE;
        }
        let result =
            unsafe { sqlite::sqlite3_open_v2(path.as_ptr(), &mut raw, flags, ptr::null()) };
        if result != sqlite::SQLITE_OK {
            let message = sqlite_message(raw, result);
            if !raw.is_null() {
                unsafe { sqlite::sqlite3_close(raw) };
            }
            return Err(RootStoreError::Sqlite(message));
        }
        Ok(Self { raw })
    }

    /// Bounds how long any statement on this connection waits out a transient
    /// SQLITE_BUSY before failing. Used by the classification probe (whose
    /// connection is otherwise lazily unconfigured) and by configure().
    pub(crate) fn set_busy_timeout_ms(&self, timeout_ms: i32) {
        unsafe { sqlite::sqlite3_busy_timeout(self.raw, timeout_ms) };
    }

    pub(crate) fn configure(&self) -> Result<(), RootStoreError> {
        self.set_busy_timeout_ms(2_000);
        let mut actual = 0;
        let defensive = unsafe {
            sqlite::sqlite3_db_config(self.raw, sqlite::SQLITE_DBCONFIG_DEFENSIVE, 1, &mut actual)
        };
        if defensive != sqlite::SQLITE_OK || actual != 1 {
            return Err(RootStoreError::Sqlite(
                "failed to enable SQLite defensive mode".to_string(),
            ));
        }
        let trusted = unsafe {
            sqlite::sqlite3_db_config(
                self.raw,
                sqlite::SQLITE_DBCONFIG_TRUSTED_SCHEMA,
                0,
                &mut actual,
            )
        };
        if trusted != sqlite::SQLITE_OK || actual != 0 {
            return Err(RootStoreError::Sqlite(
                "failed to disable SQLite trusted schema".to_string(),
            ));
        }
        self.exec(
            "PRAGMA journal_mode=DELETE; PRAGMA synchronous=FULL; PRAGMA fullfsync=ON; PRAGMA foreign_keys=ON; PRAGMA recursive_triggers=ON; PRAGMA trusted_schema=OFF; PRAGMA temp_store=MEMORY;",
        )?;
        self.verify_configuration()
    }

    fn verify_configuration(&self) -> Result<(), RootStoreError> {
        let mut defensive = 0;
        let result = unsafe {
            sqlite::sqlite3_db_config(
                self.raw,
                sqlite::SQLITE_DBCONFIG_DEFENSIVE,
                -1,
                &mut defensive,
            )
        };
        let valid = result == sqlite::SQLITE_OK
            && defensive == 1
            && self.query_text("PRAGMA journal_mode", &[])?.as_deref() == Some("delete")
            && self.query_i64("PRAGMA synchronous", &[])? == 2
            && self.query_i64("PRAGMA fullfsync", &[])? == 1
            && self.query_i64("PRAGMA foreign_keys", &[])? == 1
            && self.query_i64("PRAGMA recursive_triggers", &[])? == 1
            && self.query_i64("PRAGMA trusted_schema", &[])? == 0
            && self.query_i64("PRAGMA temp_store", &[])? == 2;
        if valid {
            Ok(())
        } else {
            Err(RootStoreError::Sqlite(
                "SQLite safety configuration was not applied exactly".to_string(),
            ))
        }
    }

    pub(crate) fn initialize_schema(&self) -> Result<(), RootStoreError> {
        self.exec(&format!(
            "PRAGMA application_id={ROOT_STORE_APPLICATION_ID}; PRAGMA user_version={ROOT_STORE_SCHEMA_VERSION}"
        ))?;
        for (_, _, _, sql) in SCHEMA_OBJECTS {
            self.exec(sql)?;
        }
        Ok(())
    }

    pub(crate) fn validate_schema(&self) -> Result<(), RootStoreError> {
        if self.query_i64("PRAGMA application_id", &[])? != ROOT_STORE_APPLICATION_ID
            || self.query_i64("PRAGMA user_version", &[])? != ROOT_STORE_SCHEMA_VERSION
        {
            return Err(RootStoreError::Integrity(
                "root store application or schema version mismatch".to_string(),
            ));
        }
        let mut actual = self.query_schema_rows()?;
        actual.sort();
        let mut expected = SCHEMA_OBJECTS
            .iter()
            .map(|(kind, name, table, sql)| {
                (
                    (*kind).to_string(),
                    (*name).to_string(),
                    (*table).to_string(),
                    (*sql).to_string(),
                )
            })
            .collect::<Vec<_>>();
        expected.sort();
        if actual != expected {
            return Err(RootStoreError::Integrity(
                "root store schema manifest mismatch".to_string(),
            ));
        }
        Ok(())
    }

    pub(crate) fn integrity_check(&self) -> Result<(), RootStoreError> {
        if self.query_text("PRAGMA quick_check", &[])?.as_deref() != Some("ok") {
            return Err(RootStoreError::Integrity(
                "SQLite quick_check failed".to_string(),
            ));
        }
        let mut statement = self.prepare("PRAGMA foreign_key_check")?;
        if statement.step()? == sqlite::SQLITE_ROW {
            return Err(RootStoreError::Integrity(
                "SQLite foreign_key_check failed".to_string(),
            ));
        }
        Ok(())
    }

    pub(crate) fn recover_uncertain_effects(&self) -> Result<(), RootStoreError> {
        self.execute(
            "UPDATE broker_operations SET state='effect-unknown', revision=revision+1 WHERE state='effect-starting' AND effect_attempt_count=1",
            &[],
        )?;
        Ok(())
    }

    pub(crate) fn release_state_tuple(&self) -> Result<(i64, i64, i64, String), RootStoreError> {
        let mut statement = self.prepare(
            "SELECT release_sequence,lease_epoch,revision,lifecycle FROM guard_metadata WHERE singleton=1",
        )?;
        if statement.step()? != sqlite::SQLITE_ROW {
            return Err(RootStoreError::Integrity(
                "root metadata is missing".to_string(),
            ));
        }
        Ok((
            statement.column_i64(0),
            statement.column_i64(1),
            statement.column_i64(2),
            statement.column_text(3)?,
        ))
    }

    pub(crate) fn exec(&self, sql: &str) -> Result<(), RootStoreError> {
        let sql = CString::new(sql)
            .map_err(|_| RootStoreError::Sqlite("SQL contains NUL".to_string()))?;
        let mut error = ptr::null_mut();
        let result = unsafe {
            sqlite::sqlite3_exec(self.raw, sql.as_ptr(), None, ptr::null_mut(), &mut error)
        };
        if result == sqlite::SQLITE_OK {
            return Ok(());
        }
        let message = if error.is_null() {
            sqlite_message(self.raw, result)
        } else {
            let message = unsafe { CStr::from_ptr(error) }
                .to_string_lossy()
                .into_owned();
            unsafe { sqlite::sqlite3_free(error.cast()) };
            message
        };
        Err(RootStoreError::Sqlite(message))
    }

    pub(crate) fn execute(
        &self,
        sql: &str,
        params: &[SqlValue<'_>],
    ) -> Result<usize, RootStoreError> {
        let mut statement = self.prepare(sql)?;
        statement.bind(params)?;
        if statement.step()? != sqlite::SQLITE_DONE {
            return Err(RootStoreError::Sqlite(
                "statement did not complete".to_string(),
            ));
        }
        Ok(unsafe { sqlite::sqlite3_changes(self.raw) as usize })
    }

    pub(crate) fn query_i64(
        &self,
        sql: &str,
        params: &[SqlValue<'_>],
    ) -> Result<i64, RootStoreError> {
        let mut statement = self.prepare(sql)?;
        statement.bind(params)?;
        if statement.step()? != sqlite::SQLITE_ROW {
            return Err(RootStoreError::Integrity(
                "query returned no row".to_string(),
            ));
        }
        Ok(statement.column_i64(0))
    }

    pub(crate) fn query_text(
        &self,
        sql: &str,
        params: &[SqlValue<'_>],
    ) -> Result<Option<String>, RootStoreError> {
        let mut statement = self.prepare(sql)?;
        statement.bind(params)?;
        if statement.step()? != sqlite::SQLITE_ROW {
            return Ok(None);
        }
        Ok(Some(statement.column_text(0)?))
    }

    pub(crate) fn query_broker_view(
        &self,
        sql: &str,
        params: &[SqlValue<'_>],
    ) -> Result<(String, i64, i64), RootStoreError> {
        let mut statement = self.prepare(sql)?;
        statement.bind(params)?;
        if statement.step()? != sqlite::SQLITE_ROW {
            return Err(RootStoreError::InvalidTransition);
        }
        Ok((
            statement.column_text(0)?,
            statement.column_i64(1),
            statement.column_i64(2),
        ))
    }

    fn query_schema_rows(&self) -> Result<Vec<(String, String, String, String)>, RootStoreError> {
        let mut statement = self.prepare(
            "SELECT type,name,tbl_name,sql FROM sqlite_schema WHERE name NOT LIKE 'sqlite_%' ORDER BY type,name",
        )?;
        let mut rows = Vec::new();
        loop {
            match statement.step()? {
                sqlite::SQLITE_ROW => {
                    if rows.len() == SCHEMA_OBJECTS.len() {
                        return Err(RootStoreError::Integrity(
                            "root store schema has extra objects".to_string(),
                        ));
                    }
                    rows.push((
                        statement.column_text(0)?,
                        statement.column_text(1)?,
                        statement.column_text(2)?,
                        statement.column_text(3)?,
                    ));
                }
                sqlite::SQLITE_DONE => return Ok(rows),
                _ => unreachable!("step only returns ROW or DONE"),
            }
        }
    }

    pub(crate) fn prepare(&self, sql: &str) -> Result<Statement, RootStoreError> {
        let sql = CString::new(sql)
            .map_err(|_| RootStoreError::Sqlite("SQL contains NUL".to_string()))?;
        let mut raw = ptr::null_mut();
        let result = unsafe {
            sqlite::sqlite3_prepare_v2(self.raw, sql.as_ptr(), -1, &mut raw, ptr::null_mut())
        };
        if result != sqlite::SQLITE_OK {
            return Err(RootStoreError::Sqlite(sqlite_message(self.raw, result)));
        }
        Ok(Statement { raw, db: self.raw })
    }
}

#[cfg(test)]
pub(crate) fn mutate_store_for_test(path: &Path, sql: &str) -> Result<(), RootStoreError> {
    let db = RootSqlite::open(path, false)?;
    db.exec(sql)
}

impl Drop for RootSqlite {
    fn drop(&mut self) {
        let result = unsafe { sqlite::sqlite3_close(self.raw) };
        debug_assert_eq!(result, sqlite::SQLITE_OK);
    }
}

pub(crate) enum SqlValue<'a> {
    Integer(i64),
    Text(&'a str),
    Blob(&'a [u8]),
}

pub(crate) struct Statement {
    raw: *mut sqlite::sqlite3_stmt,
    db: *mut sqlite::sqlite3,
}

impl Statement {
    pub(crate) fn bind(&mut self, params: &[SqlValue<'_>]) -> Result<(), RootStoreError> {
        for (offset, value) in params.iter().enumerate() {
            let index = i32::try_from(offset + 1)
                .map_err(|_| RootStoreError::Sqlite("too many SQL parameters".to_string()))?;
            let result = match value {
                SqlValue::Integer(value) => unsafe {
                    sqlite::sqlite3_bind_int64(self.raw, index, *value)
                },
                SqlValue::Text(value) => unsafe {
                    sqlite::sqlite3_bind_text(
                        self.raw,
                        index,
                        value.as_ptr().cast(),
                        i32::try_from(value.len()).map_err(|_| {
                            RootStoreError::Sqlite("SQL text parameter is too long".to_string())
                        })?,
                        sqlite::SQLITE_TRANSIENT(),
                    )
                },
                SqlValue::Blob(value) => unsafe {
                    sqlite::sqlite3_bind_blob(
                        self.raw,
                        index,
                        value.as_ptr().cast(),
                        i32::try_from(value.len()).map_err(|_| {
                            RootStoreError::Sqlite("SQL blob parameter is too long".to_string())
                        })?,
                        sqlite::SQLITE_TRANSIENT(),
                    )
                },
            };
            if result != sqlite::SQLITE_OK {
                return Err(RootStoreError::Sqlite(sqlite_message(self.db, result)));
            }
        }
        Ok(())
    }

    pub(crate) fn step(&mut self) -> Result<i32, RootStoreError> {
        let result = unsafe { sqlite::sqlite3_step(self.raw) };
        if matches!(result, sqlite::SQLITE_ROW | sqlite::SQLITE_DONE) {
            Ok(result)
        } else {
            Err(RootStoreError::Sqlite(sqlite_message(self.db, result)))
        }
    }

    pub(crate) fn column_i64(&self, column: i32) -> i64 {
        unsafe { sqlite::sqlite3_column_int64(self.raw, column) }
    }

    pub(crate) fn column_text(&self, column: i32) -> Result<String, RootStoreError> {
        let text = unsafe { sqlite::sqlite3_column_text(self.raw, column) };
        if text.is_null() {
            return Err(RootStoreError::Integrity(
                "unexpected NULL text column".to_string(),
            ));
        }
        let length = unsafe { sqlite::sqlite3_column_bytes(self.raw, column) };
        let bytes = unsafe { std::slice::from_raw_parts(text, length as usize) };
        String::from_utf8(bytes.to_vec())
            .map_err(|_| RootStoreError::Integrity("invalid UTF-8 in root store".to_string()))
    }

    pub(crate) fn column_blob(&self, column: i32) -> Result<Vec<u8>, RootStoreError> {
        let blob = unsafe { sqlite::sqlite3_column_blob(self.raw, column) };
        let length = unsafe { sqlite::sqlite3_column_bytes(self.raw, column) };
        if length < 0 || (blob.is_null() && length != 0) {
            return Err(RootStoreError::Integrity(
                "invalid blob in root store".to_string(),
            ));
        }
        if length == 0 {
            return Ok(Vec::new());
        }
        Ok(unsafe { std::slice::from_raw_parts(blob.cast(), length as usize) }.to_vec())
    }
}

impl Drop for Statement {
    fn drop(&mut self) {
        unsafe { sqlite::sqlite3_finalize(self.raw) };
    }
}

fn sqlite_message(db: *mut sqlite::sqlite3, code: i32) -> String {
    if db.is_null() {
        return format!("SQLite error {code}");
    }
    let message = unsafe { sqlite::sqlite3_errmsg(db) };
    if message.is_null() {
        format!("SQLite error {code}")
    } else {
        format!(
            "SQLite error {code}: {}",
            unsafe { CStr::from_ptr(message) }.to_string_lossy()
        )
    }
}
